---
# デバッグモードを有効にします。
debug: false

# 通知する手段を設定します。現在は Slack (webhook) のみ対応しています。
notify_by:
  - slack

# 何日前までに掲示されたお知らせを通知するかを指定します。
#    1 = 昨日と今日掲示されたお知らせを通知
#    0 = 今日掲示されたお知らせを通知
#    -1 = すべてのお知らせを通知
notify_since_days: 0

# 無視するお知らせの種類を指定します。
ignore_genres:
  #- 授業
  #- 学生呼び出し
  #- 在学生へのお知らせ
  #- 大学から学生へのお知らせ
  #- 所属組織からのお知らせ
  #- 学群授業に関するお知らせ
  #- 大学院授業に関するお知らせ
  - 期末試験、追試、レポート
  #- 資格取得に関するお知らせ
  #- 学生支援に関するお知らせ
  - 外国人留学生へのお知らせ
  #- 科目等履修生、研究生へのお知らせ
  - 落し物情報
  #- 事務からのお知らせ
  #- 学外
  #- その他

# 通知のアイコンの絵文字を指定します。
genre_emoji_map:
  授業: ':school:'
  学生呼び出し: ':tada:'
  在学生へのお知らせ: ':female-student:'
  大学から学生へのお知らせ: ':female-student:'
  所属組織からのお知らせ: ':tada:'
  学群授業に関するお知らせ: ':female-technologist:'
  大学院授業に関するお知らせ: ':female-technologist:'
  期末試験、追試、レポート: ':pencil:'
  資格取得に関するお知らせ: ':books:'
  学生支援に関するお知らせ: ':dollar:'
  外国人留学生へのお知らせ: ':earth_asia:'
  科目等履修生、研究生へのお知らせ: ':tada:'
  落し物情報: ':tada:'
  事務からのお知らせ: ':information_desk_person:'
  学外: ':tada:'
  その他: ':tada:'
  default: ':tada:' # デフォルトの絵文字を指定します。
